(function(){
  const baseOpenModal=window.openModal;
  function weatherName(key){return (W[key]?.[1]||'')+' '+(W[key]?.[0]||key)}
  function rarityText(c){return c[11]==='rare'?'HIẾM':'THƯỜNG'}
  function dCounts(){return typeof discoveryCounts==='function'?discoveryCounts():{total:Object.keys(C).length,crops:0,mutants:0}}
  function guideCard(id,c,mode){
    const locked=S.lv<c[5],seen=typeof cropDiscovered==='function'&&cropDiscovered(id),mutSeen=typeof mutantDiscovered==='function'&&mutantDiscovered(id);
    if(mode==='mutant')return `<button class="guideCard ${c[11]==='rare'?'rare':''} ${mutSeen?'mutFound':''}" onclick="showCropGuide('${id}','mutant')"><div class="guideIcon ${mutSeen?'':'mutUnknown'}">${mutSeen?'🧬':c[1]}</div><div class="guideInfo"><b>${mutSeen?c[8]:'???'}</b><span>Từ ${c[0]} • ${mutSeen?'ĐÃ KHÁM PHÁ':'CHƯA KHÁM PHÁ'}</span></div><div class="guideArrow">›</div></button>`;
    return `<button class="guideCard ${c[11]==='rare'?'rare':''} ${locked?'lockedGuide':''}" onclick="showCropGuide('${id}')"><div class="guideIcon">${c[1]}</div><div class="guideInfo"><b>${c[0]}</b><span>${rarityText(c)} • LV ${c[5]}</span><div class="guideDiscover ${seen?'ok':''}">${seen?'✓ Đã khám phá':'○ Chưa khám phá'}</div></div><div class="guideArrow">›</div></button>`
  }
  window.openGuide=function(filter='all'){
    $('#modal').classList.add('open');$('#mt').textContent='📖 Cẩm nang cây trồng';
    const counts=dCounts(),cropPct=counts.total?counts.crops/counts.total*100:0,mutPct=counts.total?counts.mutants/counts.total*100:0;
    let entries=Object.entries(C);if(filter==='normal'||filter==='rare')entries=entries.filter(([,c])=>c[11]===filter);
    const normalCount=Object.values(C).filter(c=>c[11]==='normal').length,rareCount=Object.values(C).filter(c=>c[11]==='rare').length;
    $('#mb').innerHTML=`<div class="guideSummary">Có <b>${counts.total}</b> giống cây • ${normalCount} thường • ${rareCount} hiếm</div><div class="guideProgressWrap"><div class="guideProgressCard"><b>${counts.crops}/${counts.total}</b><span>Giống đã khám phá</span><div class="guideMiniBar"><i style="width:${cropPct}%"></i></div></div><div class="guideProgressCard"><b>${counts.mutants}/${counts.total}</b><span>Đột biến đã tìm thấy</span><div class="guideMiniBar mut"><i style="width:${mutPct}%"></i></div></div></div><div class="guideTabs"><button class="${filter==='all'?'active':''}" onclick="openGuide('all')">Tất cả</button><button class="${filter==='normal'?'active':''}" onclick="openGuide('normal')">Thường</button><button class="${filter==='rare'?'active':''}" onclick="openGuide('rare')">Hiếm</button><button class="${filter==='mutant'?'active':''}" onclick="openGuide('mutant')">🧬 Đột biến</button></div><div class="guideList">${entries.map(([id,c])=>guideCard(id,c,filter)).join('')}</div>`;
  };
  window.showCropGuide=function(id,mode='crop'){
    const c=C[id];if(!c)return;const seen=typeof cropDiscovered==='function'&&cropDiscovered(id),mutSeen=typeof mutantDiscovered==='function'&&mutantDiscovered(id);
    $('#modal').classList.add('open');$('#mt').textContent=mode==='mutant'?'🧬 Bộ sưu tập đột biến':'📖 '+c[0];
    if(mode==='mutant'){
      $('#mb').innerHTML=`<div class="guideDetailHero"><div class="guideDetailIcon ${mutSeen?'':'mutUnknown'}">${mutSeen?'🧬':c[1]}</div><div><b>${mutSeen?c[8]:'???'}</b><div>${mutSeen?'Đã khám phá':'Chưa khám phá'}</div></div></div><div class="confirmCard"><div class="confirmLine"><span class="confirmLabel">Cây gốc</span><span class="confirmValue">${c[1]} ${c[0]}</span></div><div class="confirmLine"><span class="confirmLabel">Tên đột biến</span><span class="confirmValue ${mutSeen?'':'mutNameUnknown'}">${mutSeen?c[8]:'???'}</span></div><div class="confirmLine"><span class="confirmLabel">Giá bán</span><span class="confirmValue confirmTotal">${mutSeen?c[9]+'🌿':'???'}</span></div><div class="confirmLine"><span class="confirmLabel">Trạng thái</span><span class="confirmValue">${mutSeen?'✅ Đã ghi nhận':'🔒 Chưa tìm thấy'}</span></div></div><button class="ghost guideBack" onclick="openGuide('mutant')">← Quay lại bộ sưu tập</button>`;return;
    }
    $('#mb').innerHTML=`<div class="guideDetailHero"><div class="guideDetailIcon">${c[1]}</div><div><b>${c[0]}</b><div>${badge(c[11])} ${seen?'<span class="chip good">✓ Đã khám phá</span>':'<span class="chip">Chưa khám phá</span>'}</div></div></div><div class="confirmCard"><div class="confirmLine"><span class="confirmLabel">Mở khóa</span><span class="confirmValue">LV ${c[5]}</span></div><div class="confirmLine"><span class="confirmLabel">Giá hạt</span><span class="confirmValue">${c[2]}🌿</span></div><div class="confirmLine"><span class="confirmLabel">Giá bán</span><span class="confirmValue">${c[3]}🌿</span></div><div class="confirmLine"><span class="confirmLabel">Thời gian</span><span class="confirmValue">${c[4]} giây</span></div><div class="confirmLine"><span class="confirmLabel">Thời tiết ưa thích</span><span class="confirmValue">${weatherName(c[6])}</span></div><div class="confirmLine"><span class="confirmLabel">Số lứa</span><span class="confirmValue">${c[7]}</span></div><div class="confirmLine"><span class="confirmLabel">Đột biến</span><span class="confirmValue ${mutSeen?'':'mutNameUnknown'}">${mutSeen?'🧬 '+c[8]:'🧬 ???'}</span></div><div class="confirmLine"><span class="confirmLabel">Giá đột biến</span><span class="confirmValue ${mutSeen?'confirmTotal':'mutNameUnknown'}">${mutSeen?c[9]+'🌿':'???'}</span></div></div><button class="ghost guideBack" onclick="openGuide('all')">← Quay lại cẩm nang</button>`;
  };
  window.openModal=function(t){if(t==='guide')return openGuide('all');return baseOpenModal(t)};
})();